name:                99veto
version:             0.2.0.0
github:              "linus4/99veto"
license:             BSD3
author:              "Linus Weber"
maintainer:          "linus2203@freenet.de"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/linus4/99veto#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- scalpel-core
- lens
- bytestring

library:
  source-dirs: src

executables:
  99veto:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99veto

tests:
  99veto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99veto
